spring.application.name=nhom3
server.port=8080

# Đã sửa thành localhost chỉ vào máy của bạn
spring.datasource.url=jdbc:sqlserver://localhost:1433;encrypt=true;trustServerCertificate=true;databaseName=schoolmanager
spring.datasource.username=sa
spring.datasource.password=123123

spring.thymeleaf.cache=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect

# Hiển thị log SQL trên console để tiện theo dõi và debug
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# ==========================================
# CẤU HÌNH JWT (JSON WEB TOKEN)
# ==========================================
# Chuỗi bí mật (Secret Key) để ký token (Yêu cầu ít nhất 256-bit / 32 ký tự)
jwt.secret=DayLaChuoiBiMatSieuCapVoDichCuaDuAnHRManagement2026!@#
# Thời gian sống của Token (tính bằng mili giây, ví dụ 86400000 = 24 giờ)
jwt.expiration=86400000

# ==========================================
# CẤU HÌNH GỬI EMAIL (Sử dụng Gmail)
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ngocdt3102@gmail.com
# Mật khẩu ứng dụng (App Password) của Gmail, KHÔNG phải mật khẩu đăng nhập bình thường
spring.mail.password=cach qmeq tceg rwsp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true